export const GET_VOUCHER = 'GET_VOUCHER';
export const GET_VOUCHER_SUCCESS = 'GET_VOUCHER_SUCCESS';
export const GET_VOUCHER_ERROR = 'GET_VOUCHER_ERRROR';

export const BURN_VOUCHER = 'BURN_VOUCHER';
export const BURN_VOUCHER_SUCCESS = 'BURN_VOUCHER_SUCCESS';
export const BURN_VOUCHER_ERROR = 'BURN_VOUCHER_ERROR';